export type ProductType = ProductDevice | ProductLiquid
export type  ProductDevice = {
    id: string,
    category: string,
    name: string,
    price: number,
    stock: number,
    minStock: number,
    sold: number,
    image: string,
    brand: string,
    type: string,
    description: string,
    nicotineLevel: string,
    fluidLevel: string,
    flavor: string,
    batterySize: string,
    resistanceSize: string,
    coilSize: string,
    createdAt: string,
    updatedAt: string,
}

export type  ProductLiquid = {
    id: string,
    category: string,
    name: string,
    price: number,
    stock: number,
    minStock: number,
    sold: number,
    image: string,
    brand: string,
    type: string,
    description: string,
    nicotineLevel: string,
    fluidLevel: string,
    flavor: string,
    coilSize: string,
    createdAt: string,
    updatedAt: string,
}
